### ISSUE TITLE
Origin game crashes on boot after install

### ISSUE THREAD

**Issue by PretentiousGeek** [qwugfd/mempsrc#2]
If the files are installed, the Origin version crashes after the intro videos. Using -nostartupmovies just makes it crash without the videos. I tried installing when it was on the main menu, and I tried launching Multiplayer.exe after launch (although that was impossible due to the game crashing), with no difference. An re-install does nothing new and we've tried with an without admin rights.

**Comment by qwugfd** [comment]
as far as i know the origin version and the version i have on dvd are identical. what is the file size of your mirrorsedge.exe? also, there's a version 1.0.0 and a version 1.0.1. you could try applying the patch if you haven't already. the patch should be available on the internet. another thing you could try is applying a no cd fix. if you don't want the splash screen and the movies, you can just rename the files in the tdgame/splash and tdgame/movies folders. is the multiplayer.me1 in the tdgame/cookedpc/maps folder? when using the .bat for the installation it should tell you if it succeeded or failed. what does it say? does it find your mirrorsedge installation dir correctly?

what could also be the case is that you have the dlc version with the pure time trials. although at some point it was tested with that version, there have probably been changes since then and now it doesn't work with the dlc version. in that case i would recommend buying it (without the dlc) from steam, it's really cheap!

**Comment by PretentiousGeek** [comment]
After many restarts and re-installations, I finally got it working. Just replaced the Mutliplayer.me1 file in the maps folder. Thank you :)
